program: main.py
method: random
metric:
  name: Validation Loss
  goal: minimize
parameter:
  learning_rate:
    min: 0.0003
    max: 0.03
  batch_size:
    min: 4
    max: 32
  weight_decay:
    min: 0.0001
    max: 0.01
